services:
  - type: web
    name: freaky-four-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables in Render dashboard:
    # - MONGO_URI (your MongoDB connection string)
    # - JWT_SECRET (your JWT secret key)
    # - Any other environment variables your app needs
